/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.dto.AccessTokenDTO;
import life.majiang.community.provider.GiteeProvider;
import life.majiang.community.provider.dto.GiteeUser;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GiteeProvider_SSTest extends GiteeProvider_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getUser_0()  throws Throwable  {
      GiteeProvider giteeProvider0 = new GiteeProvider();
      GiteeUser giteeUser0 = giteeProvider0.getUser("");
      assertNull(giteeUser0);
  }
  }
