/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.dto.AccessTokenDTO;
import life.majiang.community.provider.GithubProvider;
import life.majiang.community.provider.dto.GithubUser;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GithubProvider_SSTest extends GithubProvider_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getUser_0()  throws Throwable  {
      GithubProvider githubProvider0 = new GithubProvider();
      GithubUser githubUser0 = githubProvider0.getUser("/S`ZG");
      assertNull(githubUser0);
  }
  }
