/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.provider.UFileProperties;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UFileProperties_SSTest extends UFileProperties_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setExpiresDuration_00()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();
      Integer integer0 = new Integer(411);

      //invoke method for uFileProperties0
      uFileProperties0.setExpiresDuration(integer0);

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getBucketType());
  }
  @Test(timeout = 4000)
  public void test_setUploadDomain_01()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setUploadDomain(")");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getExpiresDuration());
  }
  @Test(timeout = 4000)
  public void test_setPrivateKey_02()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setPrivateKey("1");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getExpiresDuration());
  }
  @Test(timeout = 4000)
  public void test_setPublicKey_03()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setPublicKey("43");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getDownloadDomain());
  }
  @Test(timeout = 4000)
  public void test_canEqual_04()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();
      Object object0 = PrivateAccess.callMethod((Class<UFileProperties>) UFileProperties.class, uFileProperties0, "canEqual", (Object) "amdHYa*AcZ", (Class<?>) Object.class);
      assertEquals(false, object0);
  }
  @Test(timeout = 4000)
  public void test_setBucketType_05()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setBucketType("'STCl#:[{");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getPublicKey());
  }
  @Test(timeout = 4000)
  public void test_setBucketName_06()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setBucketName("_2gu?TXV:1Y}/]");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getExpiresDuration());
  }
  @Test(timeout = 4000)
  public void test_setDownloadDomain_07()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.setDownloadDomain("1.0");

      //invoke method for uFileProperties0
      assertNull(uFileProperties0.getUploadDomain());
  }
  @Test(timeout = 4000)
  public void test_equals_08()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.getExpiresDuration();
      boolean boolean0 = uFileProperties0.equals("life.majiang.community.provider.UFileProperties");
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_hashCode_09()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_10()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.getExpiresDuration();

      //invoke method for uFileProperties0
      uFileProperties0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_getPublicKey_11()  throws Throwable  {
      UFileProperties uFileProperties0 = new UFileProperties();

      //invoke method for uFileProperties0
      uFileProperties0.getExpiresDuration();
      String string0 = uFileProperties0.toString();
      assertEquals("UFileProperties(publicKey=null, privateKey=null, bucketName=null, uploadDomain=null, downloadDomain=null, bucketType=null, expiresDuration=null)", string0);
  }}
