/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.provider.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.provider.dto.GiteeUser;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GiteeUser_SSTest extends GiteeUser_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setId_00()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();
      Long long0 = new Long(0L);

      //invoke method for giteeUser0
      giteeUser0.setId(long0);

      //invoke method for giteeUser0
      assertNull(giteeUser0.getBio());
  }
  @Test(timeout = 4000)
  public void test_setAvatarUrl_01()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.setAvatarUrl(")");

      //invoke method for giteeUser0
      assertNull(giteeUser0.getBio());
  }
  @Test(timeout = 4000)
  public void test_setBio_02()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.setBio("C=o_8N");

      //invoke method for giteeUser0
      assertEquals("C=o_8N", giteeUser0.getBio());
  }
  @Test(timeout = 4000)
  public void test_setName_03()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.setName("59");

      //invoke method for giteeUser0
      assertNull(giteeUser0.getAvatarUrl());
  }
  @Test(timeout = 4000)
  public void test_equals_04()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();
      boolean boolean0 = giteeUser0.equals(giteeUser0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_05()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();
      boolean boolean0 = giteeUser0.equals("GiteeUser(name=");
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_06()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();
      GiteeUser giteeUser1 = new GiteeUser();
      boolean boolean0 = giteeUser1.equals(giteeUser0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_07()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();
      GiteeUser giteeUser1 = new GiteeUser();
      boolean boolean0 = giteeUser0.equals(giteeUser1);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_hashCode_08()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_09()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();

      //invoke method for giteeUser0
      giteeUser0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_toString_10()  throws Throwable  {
      GiteeUser giteeUser0 = new GiteeUser();

      //invoke method for giteeUser0
      giteeUser0.getId();
      String string0 = giteeUser0.toString();
      assertEquals("GiteeUser(name=null, id=null, bio=null, avatarUrl=null)", string0);
  }}
