/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import life.majiang.community.dto.QuestionQueryDTO;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class QuestionQueryDTO_SSTest extends QuestionQueryDTO_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setPage_0()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();
      Integer integer0 = new Integer(0);

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setPage(integer0);

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getTime());
  }
  @Test(timeout = 4000)
  public void test_setTime_1()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();
      Long long0 = new Long(0L);

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setTime(long0);

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getPage());
  }
  @Test(timeout = 4000)
  public void test_setSearch_2()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setSearch(", page=");

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getTime());
  }
  @Test(timeout = 4000)
  public void test_setSize_3()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();
      Integer integer0 = new Integer(0);

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setSize(integer0);

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getSearch());
  }
  @Test(timeout = 4000)
  public void test_setSort_4()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setSort(":n1\"(bFS]nxD0=H9u9O");

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getSearch());
  }
  @Test(timeout = 4000)
  public void test_setTag_5()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.setTag("1");

      //invoke method for questionQueryDTO0
      assertNull(questionQueryDTO0.getSearch());
  }
  @Test(timeout = 4000)
  public void test_equals_6()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.getPage();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.getTime();
      boolean boolean0 = questionQueryDTO0.equals(")");
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_toString_7()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();
      String string0 = questionQueryDTO0.toString();
      assertEquals("QuestionQueryDTO(search=null, sort=null, time=null, tag=null, page=null, size=null)", string0);
  }
  @Test(timeout = 4000)
  public void test_hashCode_8()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_9()  throws Throwable  {
      QuestionQueryDTO questionQueryDTO0 = new QuestionQueryDTO();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.getPage();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.getTime();

      //invoke method for questionQueryDTO0
      questionQueryDTO0.hashCode();
  }}
