/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import life.majiang.community.CommunityApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CommunityApplication_SSTest extends CommunityApplication_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      CommunityApplication communityApplication0 = new CommunityApplication();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        CommunityApplication.main(stringArray0);
      
      } catch(Throwable e) {
         //
         // Exception Name: NullPointerException
         // no message in exception (getMessage() returned null)
         //
      }
  }}
