/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.cache;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import java.util.List;
import life.majiang.community.cache.QuestionCache;
import life.majiang.community.dto.QuestionDTO;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class QuestionCache_SSTest extends QuestionCache_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getStickies_0()  throws Throwable  {
      QuestionCache questionCache0 = new QuestionCache();
      List<QuestionDTO> list0 = questionCache0.getStickies();
      assertTrue(list0.isEmpty());
  }}
