/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.life.majiang.community.cache;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import java.util.List;
import life.majiang.community.cache.TagCache;
import life.majiang.community.dto.TagDTO;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TagCache_SSTest extends TagCache_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      TagCache.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }
  @Test(timeout = 4000)
  public void test_get_1()  throws Throwable  {
      TagCache tagCache0 = new TagCache();
      List<TagDTO> list0 = TagCache.get();
      assertEquals(5, list0.size());
  }
  @Test(timeout = 4000)
  public void test_filterInvalid_2()  throws Throwable  {
      String string0 = TagCache.filterInvalid(", ");
      assertEquals(" ", string0);
  }
  @Test(timeout = 4000)
  public void test_filterInvalid_3()  throws Throwable  {
      String string0 = TagCache.filterInvalid("1");
      assertEquals("1", string0);
  }
  @Test(timeout = 4000)
  public void test_filterInvalid_4()  throws Throwable  {
      String string0 = TagCache.filterInvalid("objective-c");
      assertEquals("", string0);
  }}
